color: null
description: null
fieldLayouts:
  6e3255ed-c906-4c9c-99ba-5852941f48c6:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-05-26T13:34:14+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 71ace60b-1def-4289-b954-835d70c7f96f # Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4f553c9f-1a6f-482e-8d76-379ce32d4eab
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2026-05-26T13:36:19+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 71ace60b-1def-4289-b954-835d70c7f96f # Title
            handle: commonTitle2
            includeInCards: false
            instructions: null
            label: 'Title line 2'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7d7dc348-c967-49c0-a05f-9d2ea839eb2a
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2026-05-26T13:34:14+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5705b456-77ec-47e8-8e23-19798b3e4884 # Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ecda1bd5-446b-4aa1-bf73-23cd273ae3dd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-26T13:34:14+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 951be517-f918-4494-b1f0-db3ffbd712f1 # ContactData
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2441fc9b-2096-4b58-a238-f9481db65641
            userCondition: null
            warning: null
            width: 100
        name: Common
        uid: 3a91311d-31f4-4bc1-85e7-cf3578aed384
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-05-26T13:34:14+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0659686e-097b-4429-827c-0abdf454b88a # Seo
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4338a900-7d73-4790-965f-50c74c858d71
            userCondition: null
            warning: null
            width: 100
        name: Seo
        uid: d21fcf25-4f16-485a-8755-843d57afe0d3
        userCondition: null
handle: contact
hasTitleField: false
icon: null
name: Contact
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
