color: null
description: null
fieldLayouts:
  a7268720-d932-4c9a-96eb-abbff6ef2b26:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 841f544c-33b2-4b34-b400-d8d2503d5680
            handle: null
            includeInCards: true
            instructions: null
            label: Title
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ea8c792b-cc55-4497-b4b7-ea0ed264e34b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: e1d8c407-dd15-416f-999d-576c5c96be62 # Home Body Blocks - Home Shoots Block - Description
            handle: null
            includeInCards: false
            instructions: null
            label: Description
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 473e7475-7b9f-4b69-a5ca-a0003d611760
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 1d54fa5c-6327-4b22-ab81-e7f629881ef0
            handle: null
            includeInCards: false
            instructions: null
            label: Projects
            providesThumbs: true
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ef072af2-463a-47e2-a5bf-6b5d220f073a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 16955ca2-9227-4746-bde1-6fb555375e8e
        userCondition: null
handle: mxHomeShootsBlock
hasTitleField: false
icon: null
name: 'Home Shoots Block'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
