color: null
description: null
fieldLayouts:
  a7268720-d932-4c9a-96eb-abbff6ef2b26:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-05-24T11:09:06+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 1d54fa5c-6327-4b22-ab81-e7f629881ef0
            handle: null
            includeInCards: false
            instructions: null
            label: Projects
            providesThumbs: true
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ef072af2-463a-47e2-a5bf-6b5d220f073a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 16955ca2-9227-4746-bde1-6fb555375e8e
        userCondition: null
handle: mxHomeShootsBlock
hasTitleField: false
icon: null
name: 'Home Shoots Block'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
