color: null
description: null
fieldLayouts:
  52abaffc-d949-4029-b089-46fcb5cd5789:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-05-24T11:03:23+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 30092d52-d209-4de3-85da-178cb325cce7 # Home Body Blocks
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ee81e950-8b4a-42d1-a455-259040cf5a6a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-24T11:03:23+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 97fe6551-4a72-467e-9f94-995cf5a71309
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b16181a7-6e39-4b0d-984c-6e247909a84a
            userCondition: null
            warning: null
            width: 100
        name: Body
        uid: 95538380-6841-426a-9ef4-af3bb8c7ffb5
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-05-24T11:03:23+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0659686e-097b-4429-827c-0abdf454b88a # Seo
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a3fef493-57e5-416b-a9ee-42788f362475
            userCondition: null
            warning: null
            width: 100
        name: Seo
        uid: 73b59d88-5af4-41dd-a906-b3357417d029
        userCondition: null
handle: pageHome
hasTitleField: false
icon: null
name: 'Home '
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
