color: null
description: null
fieldLayouts:
  dbe91ffa-9934-4d9e-9c94-81070682199b:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-05-26T13:57:18+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 71ace60b-1def-4289-b954-835d70c7f96f # Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 65218108-2711-4453-bc8a-8ec0a301ab44
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-26T13:57:18+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e47a706d-baae-4765-883f-bc8563ac1d71 # Intro
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2752c199-9c09-416c-90e8-a4750b734ae9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-26T13:57:18+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 21d787fa-27ea-4de6-ab7f-8e4b98bd35db # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1f26219e-2019-47f4-908f-383cfaabbc89
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-26T13:57:18+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0df14fe0-bee1-457a-8cac-730a4358935f # Header Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 48b37b41-805c-4f51-8442-ada795234eaa
            userCondition: null
            warning: null
            width: 100
        name: General
        uid: 6460418e-2c66-4b4a-bd18-a909b1be758c
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-05-26T13:57:18+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0659686e-097b-4429-827c-0abdf454b88a # Seo
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5646e3fc-3b0f-418c-97ac-01e1f4955988
            userCondition: null
            warning: null
            width: 100
        name: Seo
        uid: 702a56c8-0359-4158-a24f-1d0cc4adb98d
        userCondition: null
handle: pageStudio
hasTitleField: false
icon: null
name: 'Page studio'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
