color: null
description: null
fieldLayouts:
  ac062e59-2d14-4f1b-9b65-3627676c6a2f:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-06-02T12:08:26+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5705b456-77ec-47e8-8e23-19798b3e4884 # Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e124822e-5646-46d2-9ed8-aa949dbeab43
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-06-02T12:08:26+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: fd7aa02b-bd43-4fb2-a7e0-e437bdf27c22 # prices
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 60e05376-3b57-42f1-a4e9-7a3bfc7d9859
            userCondition: null
            warning: null
            width: 100
        name: Common
        uid: bb2206ec-7842-4819-a294-bdfe386b8e2f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-06-02T12:08:26+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0659686e-097b-4429-827c-0abdf454b88a # Seo
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c759c4ed-616b-4946-a72b-699bb6fb45fb
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: d0523bc9-0cad-45a1-81ee-ebdca7f4ec83
        userCondition: null
handle: pagePrijzen
hasTitleField: false
icon: null
name: Prijzen
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
