fieldLayouts:
  dbe91ffa-9934-4d9e-9c94-81070682199b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d4c563fb-fa54-475d-8b12-99e579b10287
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 71ace60b-1def-4289-b954-835d70c7f96f # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 65218108-2711-4453-bc8a-8ec0a301ab44
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e47a706d-baae-4765-883f-bc8563ac1d71 # Studio paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2752c199-9c09-416c-90e8-a4750b734ae9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 21d787fa-27ea-4de6-ab7f-8e4b98bd35db # Studio paragraph 2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1f26219e-2019-47f4-908f-383cfaabbc89
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a1e53f92-6af3-411e-b427-42b37107382b # Studio quote
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e81a786f-ff69-4dd1-af64-5d97b4c4e36e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0df14fe0-bee1-457a-8cac-730a4358935f # Header Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 48b37b41-805c-4f51-8442-ada795234eaa
            userCondition: null
            warning: null
            width: 100
        name: General
        uid: 6460418e-2c66-4b4a-bd18-a909b1be758c
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0659686e-097b-4429-827c-0abdf454b88a # Seo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5646e3fc-3b0f-418c-97ac-01e1f4955988
            userCondition: null
            warning: null
            width: 100
        name: Seo
        uid: 702a56c8-0359-4158-a24f-1d0cc4adb98d
        userCondition: null
handle: pageStudio
hasTitleField: false
name: 'Page studio'
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
