color: null
description: null
fieldLayouts:
  17c301c6-0f2c-43b6-af70-6a0cc4ee1a2f:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-05-24T16:09:37+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f31da9ea-4646-4253-8396-66574a04e1e0 # Portfolio Albums
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4746651f-4d2b-42f8-9149-e682b8046045
            userCondition: null
            warning: null
            width: 100
        name: Body
        uid: 9ae87410-c676-4ac7-b3f8-cfdc06dd88c0
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-05-24T16:09:37+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 71ace60b-1def-4289-b954-835d70c7f96f # Title
            handle: null
            includeInCards: false
            instructions: ' '
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c281dec1-c83e-4949-9d0c-67c4f4a8dd84
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-24T16:09:37+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5705b456-77ec-47e8-8e23-19798b3e4884 # Description
            handle: null
            includeInCards: false
            instructions: ' '
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 72cf0182-748f-41ad-991b-20dd98e704a7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-24T16:09:37+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 4ba47aec-1758-4437-bcd2-775fc3066311 # Link
            handle: null
            includeInCards: false
            instructions: ' '
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 40d6ff32-cf27-48eb-b01a-3e9b6c519628
            userCondition: null
            warning: null
            width: 100
        name: 'Call to action'
        uid: b4202a97-0a13-4abf-9181-26561abf689f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-05-24T16:09:37+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0659686e-097b-4429-827c-0abdf454b88a # Seo
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c5a3f334-a308-4dca-ac02-0b3efef3012e
            userCondition: null
            warning: null
            width: 100
        name: Seo
        uid: c88e1ac0-bfec-46c2-8c9b-1a74739c795e
        userCondition: null
handle: pagePortfolio
hasTitleField: false
icon: null
name: Portfolio
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: Portfolio
titleTranslationKeyFormat: null
titleTranslationMethod: site
