columnSuffix: null
contentColumnType: text
handle: commonTitle
instructions: 'Add title that will be shown in the header'
name: Title
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: text
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
