columnSuffix: null
handle: contactText
instructions: 'This could be an address or a little note.'
name: 'ContactData - ContactText - Text'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 2
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
