columnSuffix: null
contentColumnType: text
handle: homeQuote
instructions: 'Add a quote to the homepage. The quote will be displayed on top of the header image.'
name: 'Home Quote'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: text
  initialRows: 4
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
