defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 9a58a80f-9c56-4570-a88d-9e28b651f603 # Contact
handle: contact
maxAuthors: 1
name: Contact
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  fc09fd9c-5a1a-4c16-97e8-a208d962d92b: # Studio Coup De Foudre
    enabledByDefault: true
    hasUrls: true
    template: pages/contact/index
    uriFormat: contact
type: single
