defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 9b75ce17-ff83-4745-85bf-94feaea3ba6a # Prijzen
handle: pagePrijzen
maxAuthors: 1
name: Prijzen
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  fc09fd9c-5a1a-4c16-97e8-a208d962d92b: # Studio Coup De Foudre
    enabledByDefault: true
    hasUrls: true
    template: pages/prijzen/index
    uriFormat: prijzen
type: single
