defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 23e5b070-68ff-4f00-b5da-29e2417cb874 # Portfolio
handle: pagePortfolio
maxAuthors: 1
name: Portfolio
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  fc09fd9c-5a1a-4c16-97e8-a208d962d92b: # Studio Coup De Foudre
    enabledByDefault: true
    hasUrls: true
    template: /pages/portfolio/entry.twig
    uriFormat: portfolio
type: single
