defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: d327e0d4-c102-4266-9253-894927b5a8ca # Project
handle: project
maxAuthors: 1
name: Projects
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  fc09fd9c-5a1a-4c16-97e8-a208d962d92b: # Studio Coup De Foudre
    enabledByDefault: true
    hasUrls: true
    template: pages/project/entry
    uriFormat: 'project/{slug}'
type: channel
